#!/usr/bin/env python3
"""Scaffold a starter Beancount ledger for one set of books from the config.

Usage: init_beancount.py --config <config.yaml> --set <set-id> --out <ledger dir>

Writes main.beancount, accounts.beancount, opening.beancount. Run `bean-check
<out>/main.beancount` afterward (it should pass with zero transactions).
"""
import argparse, os, re, sys

ROOTS = {"Assets", "Liabilities", "Equity", "Income", "Expenses"}


def tok(s):
    """A valid Beancount sub-account token: TitleCase, alphanumerics only."""
    parts = re.findall(r"[A-Za-z0-9]+", s or "")
    if not parts:
        return "X"
    t = "".join(p[:1].upper() + p[1:] for p in parts)
    return t if re.match(r"[A-Z0-9]", t) else "X" + t


def valid_account(a):
    comps = (a or "").split(":")
    if not comps or comps[0] not in ROOTS:
        return None
    return ":".join([comps[0]] + [tok(c) for c in comps[1:]])


def main():
    try:
        import yaml
    except ImportError:
        sys.exit("pyyaml required: pip install pyyaml --break-system-packages")
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--set", required=True, dest="setid")
    ap.add_argument("--out", required=True)
    ap.add_argument("--open-date", default="2000-01-01")
    a = ap.parse_args()

    with open(a.config) as f:
        cfg = yaml.safe_load(f)
    sets = {s["id"]: s for s in cfg.get("sets_of_books", [])}
    if a.setid not in sets:
        sys.exit(f"set '{a.setid}' not found in config")
    s = sets[a.setid]
    currency = (cfg.get("company", {}).get("locality", {}) or {}).get("currency", "USD")
    fye = s.get("fiscal_year_end") or cfg.get("company", {}).get("fiscal_year_end", "12-31")

    role_root = {"operating": "Assets:Bank", "savings": "Assets:Bank", "tax": "Assets:Bank",
                 "card": "Liabilities:CreditCard", "loc": "Liabilities:LOC"}
    opens = []
    for ac in cfg.get("accounts", []):
        if ac.get("set") != a.setid:
            continue
        root = role_root.get(ac.get("role", "operating"), "Assets:Bank")
        base = tok(ac.get("name", "Account"))
        acct = f"{root}:{base}{ac['last4']}" if ac.get("last4") else f"{root}:{base}"
        opens.append((acct, ac.get("name", "")))

    ov = cfg.get("overlap", {}) or {}
    for k in ("shareholder_loan_account", "due_from_business_account"):
        if ov.get(k):
            va = valid_account(ov[k])
            if va:
                opens.append((va, k))

    # Income/Expense categories: seed from the accountant's chart of accounts
    # (prior_financials.chart_of_accounts for this set) so the user starts on the
    # categories their accountant used; otherwise fall back to Uncategorized.
    coa = {}
    for pf in cfg.get("prior_financials", []) or []:
        if pf.get("set") == a.setid:
            coa = pf.get("chart_of_accounts", {}) or {}
            break
    for cat in coa.get("income", []) or []:
        opens.append((f"Income:{tok(cat)}", f"accountant category: {cat}"))
    for cat in coa.get("expenses", []) or []:
        opens.append((f"Expenses:{tok(cat)}", f"accountant category: {cat}"))
    if not (coa.get("income") or coa.get("expenses")):
        opens.append(("Income:Uncategorized", "standard"))
        opens.append(("Expenses:Uncategorized", "standard"))
    opens.append(("Equity:Opening-Balances", "standard"))

    seen, uniq = set(), []
    for acct, note in opens:
        if acct not in seen:
            seen.add(acct)
            uniq.append((acct, note))

    os.makedirs(a.out, exist_ok=True)
    od = a.open_date
    with open(os.path.join(a.out, "accounts.beancount"), "w") as f:
        f.write(f";; Accounts for set: {s.get('label', a.setid)} (generated)\n\n")
        for acct, note in uniq:
            comment = f"  ; {note}" if note and note != "standard" else ""
            f.write(f"{od} open {acct}{comment}\n")
    with open(os.path.join(a.out, "opening.beancount"), "w") as f:
        f.write(";; Opening balances - fill from statements, e.g.:\n")
        f.write(f";; {od} pad Assets:Bank:Example Equity:Opening-Balances\n")
        f.write(f";; {od} balance Assets:Bank:Example  0.00 {currency}\n")
    with open(os.path.join(a.out, "main.beancount"), "w") as f:
        f.write(f';; {s.get("label", a.setid)} - Beancount ledger (generated by finance-organizer)\n')
        f.write(f'option "title" "{s.get("label", a.setid)}"\n')
        f.write(f'option "operating_currency" "{currency}"\n')
        f.write('option "render_commas" "TRUE"\n\n')
        f.write(f'1970-01-01 custom "fava-option" "fiscal-year-end" "{fye}"\n\n')
        f.write('include "accounts.beancount"\n')
        f.write('include "opening.beancount"\n')
        f.write(';; add monthly files here, e.g.  include "fy2026-09.beancount"\n')
    print(f"wrote {a.out} -> {len(uniq)} accounts ({currency}, FYE {fye}); run bean-check next")


if __name__ == "__main__":
    main()
